Profile screen
Dis-Place/sdp2022 pull request #55
Opened 2022-03-16 12:55 UTC by fesqvw

2022-03-16 13:29 UTC, Matthieu-Andre requested changes
Good job, code looks good.
Small nitpicks: there are some lines that have a redundant semicolon and some methods have parameters that they never use.
(also I think it's too much code for one pr, making it time intensive to review)

2022-03-16 13:29 UTC, Matthieu-Andre commented on app/src/main/java/com/github/blecoeur/bootcamp/profile/ProfileActivity.kt
> +        historyRecyclerView.layoutManager = LinearLayoutManager(applicationContext);
There are some redundant semicolons on lines 39,45,51,57,63

2022-03-16 13:29 UTC, Matthieu-Andre commented on app/src/main/java/com/github/blecoeur/bootcamp/profile/ProfileActivity.kt
> +    fun profileButton(view : View){
profileButton, inboxButton, friendsButton and settingButton all have a view parameter that is never used in theses methods

2022-03-16 17:15 UTC, Matthieu-Andre approved these changes
thanks for the fixes

2022-03-17 18:24 UTC, dante11111111111 approved these changes

2022-03-17 18:33 UTC, Blecoeur commented on app/src/main/java/com/github/blecoeur/bootcamp/profile/ProfileActivity.kt
> +        achRecyclerView.layoutManager = LinearLayoutManager(applicationContext)
You could maybe replace it by a private function setup archRecyclerView

2022-03-17 18:33 UTC, Blecoeur commented on app/src/main/java/com/github/blecoeur/bootcamp/profile/ProfileActivity.kt
> +        statRecyclerView.layoutManager = LinearLayoutManager(applicationContext)
Same as archRecycleView

2022-03-17 18:36 UTC, Blecoeur approved these changes
Please avoid doing 57-files-changed PR,

2022-03-17 19:16 UTC, merged